targets:
  $default:
    builders:
      file_based_router_generator:
        enabled: true

builders:
  file_based_router_generator:
    import: 'package:file_based_router_generator/builder.dart'
    builder_factories: ['fileRouterBuilder']
    build_extensions: {'.dart': ['.fr.g.dart']}
    auto_apply: dependents
    build_to: source
    applies_builders: ['source_gen|combining_builder']
